server.name: kibana
server.host: "0.0.0.0"
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.monitoring.ui.container.elasticsearch.enabled: false
xpack.reporting.enabled: false
xpack.security.enabled: false
logging.verbose: false