version: '3.3'
services:
  dynacore_logstash:
    image: logstash:5.6
    ports:
      - 25000:25000/udp
    networks:
      - myapp_api
      - myapp_db
networks:
  myapp_api:
    external: true
  myapp_db:
    external: true
